spring.application.name=fixlab

# Configuraci�n de la base de datos para FixLab
spring.datasource.url=jdbc:postgresql://localhost:5432/fixlab
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuraci�n de JPA / Hibernate para creaci�n autom�tica
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opcional: para ver mejor las consultas en consola
spring.jpa.properties.hibernate.format_sql=true

