spring.application.name=fixlab
server.port=8081

# Configuraci�n de la base de datos para FixLab
spring.datasource.url=jdbc:postgresql://localhost:5432/fixlab
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuraci�n de JPA / Hibernate para creaci�n autom�tica
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opcional: para ver mejor las consultas en consola
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970



# Configuraci�n de Cloudinary para im�genes del Cat�logo
cloudinary.cloud-name=dgwmwo0ui
cloudinary.api-key=268538129727797
cloudinary.api-secret=qKTGD9tS20piadVcuAokXYq7pjo


# Configuraci�n de Mercado Pago
mercadopago.access-token=APP_USR-238288360168399-030100-970efd69935326292a37b7fd38613d31-3233058764
