spring.application.name=fixlab
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/fixlab
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Configuraci n de Cloudinary para im genes del Cat logo
cloudinary.cloud-name=dgwmwo0ui
cloudinary.api-key=268538129727797
cloudinary.api-secret=qKTGD9tS20piadVcuAokXYq7pjo


<<<<<<< HEAD
# Configuraci�n Wompi (Pruebas)
wompi.public-key=pub_test_XXXXXXXXXXXX
wompi.integrity-secret=test_integrity_XXXXXXXXXXXX
wompi.currency=COP



# ==========================================
# CONFIGURACI�N DE CORREO (GMAIL SMTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=labfix64@gmail.com
spring.mail.password=wcjidmqttlifugtm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
=======
# Configuraci n de Mercado Pago
mercadopago.access-token=APP_USR-238288360168399-030100-970efd69935326292a37b7fd38613d31-3233058764














>>>>>>> ebc21313413cb4bf66ee58a55f8bed5b9e914097
