spring.application.name=fixlab

# Puerto del backend (el frontend apunta a http://localhost:8081)
server.port=8081

# Configuraci�n de la base de datos para FixLab
spring.datasource.url=jdbc:postgresql://localhost:5432/fixlab
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuraci�n de JPA / Hibernate para creaci�n autom�tica
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opcional: para ver mejor las consultas en consola
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970



# Configuraci�n de Cloudinary para im�genes del Cat�logo
cloudinary.cloud-name=dgwmwo0ui
cloudinary.api-key=268538129727797
cloudinary.api-secret=qKTGD9tS20piadVcuAokXYq7pjo


# Llaves de Wompi Sandbox
wompi.public-key=pub_test_KnyMLNmbt5UlEwzgzUTJvSevrGoX9Af1
wompi.integrity-secret=test_integrity_RAi1hTTSrgA0lHiTON3V8jdUPP6zOi1Q
wompi.events-secret=test_events_bY5YCJ4yzKVHSJVXHumNq7WMxxSUZqZm
wompi.currency=prv_test_dYnIPZnj2D4hvuGvkCkA2dk9m3dCGjeS




# ==========================================
# CONFIGURACI�N DE CORREO (GMAIL SMTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=labfix64@gmail.com
spring.mail.password=wcjidmqttlifugtm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*